import * as XLSX from 'xlsx'
import formatDate, { formatDateTime } from '@/lib/formatDate';

export interface ExportData {
  sheetName: string
  data: Array<Record<string, any>>
}

export const generateXLSXReport = (reportData: ExportData[], filename: string): void => {
  const workbook = XLSX.utils.book_new()
  
  reportData.forEach((sheet) => {
    const worksheet = XLSX.utils.json_to_sheet(sheet.data)
    
    // Auto-size columns
    const range = XLSX.utils.decode_range(worksheet['!ref'] || 'A1')
    const colWidths: number[] = []
    
    for (let col = range.s.c; col <= range.e.c; col++) {
      let maxWidth = 10
      for (let row = range.s.r; row <= range.e.r; row++) {
        const cellAddress = XLSX.utils.encode_cell({ r: row, c: col })
        const cell = worksheet[cellAddress]
        if (cell && cell.v) {
          const cellLength = cell.v.toString().length
          maxWidth = Math.max(maxWidth, cellLength + 2)
        }
      }
      colWidths[col] = Math.min(maxWidth, 50) // Cap at 50 characters
    }
    
    worksheet['!cols'] = colWidths.map(width => ({ width }))
    
    XLSX.utils.book_append_sheet(workbook, worksheet, sheet.sheetName)
  })
  
  // Add metadata sheet
  const metadata = [
    { Property: 'Generated On', Value: formatDateTime(new Date()) },
    { Property: 'Generated By', Value: 'Jira Insight Platform' },
    { Property: 'Report Type', Value: 'Resource Strategy Analysis' }
  ]
  const metaSheet = XLSX.utils.json_to_sheet(metadata)
  XLSX.utils.book_append_sheet(workbook, metaSheet, 'Metadata')
  
  // Download
  const finalFilename = `${filename}_${new Date().toISOString().split('T')[0]}.xlsx`
  XLSX.writeFile(workbook, finalFilename)
}

export const generateGrowthTeamXLSX = (data: {
  overview: any[]
  profitability: any[]
  utilization: any[]
  projects: any[]
}): void => {
  const exportData: ExportData[] = [
    {
      sheetName: 'Overview',
      data: data.overview
    },
    {
      sheetName: 'Client Profitability',
      data: data.profitability
    },
    {
      sheetName: 'Resource Utilization',
      data: data.utilization
    },
    {
      sheetName: 'Project Portfolio',
      data: data.projects
    }
  ]
  
  generateXLSXReport(exportData, 'growth_team_report')
}

export const generateProjectManagerXLSX = (data: {
  projects: any[]
  team: any[]
  conflicts: any[]
  timeline: any[]
}): void => {
  const exportData: ExportData[] = [
    {
      sheetName: 'Project Health',
      data: data.projects
    },
    {
      sheetName: 'Team Performance',
      data: data.team
    },
    {
      sheetName: 'Resource Conflicts',
      data: data.conflicts
    },
    {
      sheetName: 'Timeline Analysis',
      data: data.timeline
    }
  ]
  
  generateXLSXReport(exportData, 'project_manager_report')
}

export const generateAllocationXLSX = (
  allocations: any[],
  consultants: any[],
  projects: any[]
): void => {
  // Prepare allocation data with joined information
  const allocationData = allocations.map(allocation => {
    const consultant = consultants.find(c => c.id === allocation.consultantId)
    const project = projects.find(p => p.id === allocation.projectId)
    
    return {
      'Consultant': consultant?.name || 'Unknown',
      'Project': project?.name || 'Unknown Project',
      'Client': project?.clientName || 'Unknown Client',
      'Role': allocation.roleInProject || 'Consultant',
      'Hours per Week': allocation.hoursPerWeek,
  'Start Date': formatDate(allocation.startDate),
  'End Date': formatDate(allocation.endDate),
      'Status': allocation.status,
      'Hourly Rate': consultant?.hourlyRate ? `$${consultant.hourlyRate}` : 'N/A',
      'Weekly Cost': consultant?.hourlyRate 
        ? `$${(consultant.hourlyRate * allocation.hoursPerWeek).toFixed(2)}` 
        : 'N/A'
    }
  })
  
  // Prepare consultant utilization summary
  const consultantSummary = consultants.map(consultant => {
    const consultantAllocations = allocations.filter(a => a.consultantId === consultant.id)
    const totalHours = consultantAllocations.reduce((sum, a) => sum + a.hoursPerWeek, 0)
    const utilization = ((totalHours / 40) * 100).toFixed(1) // Assuming 40h work week
    
    return {
      'Consultant': consultant.name,
      'Role': consultant.role,
      'Department': consultant.department || 'N/A',
      'Skills': consultant.skills || 'N/A',
      'Hourly Rate': consultant.hourlyRate ? `$${consultant.hourlyRate}` : 'N/A',
      'Total Allocated Hours': totalHours,
      'Utilization %': `${utilization}%`,
      'Active Projects': consultantAllocations.length,
      'Status': totalHours > 40 ? 'Overallocated' : totalHours < 32 ? 'Underutilized' : 'Optimal'
    }
  })
  
  // Prepare project summary
  const projectSummary = projects.map(project => {
    const projectAllocations = allocations.filter(a => a.projectId === project.id)
    const totalHours = projectAllocations.reduce((sum, a) => sum + a.hoursPerWeek, 0)
    const teamSize = projectAllocations.length
    
    return {
      'Project': project.name,
      'Client': project.clientName || 'Unknown Client',
      'Status': project.status,
      'Priority': project.priority,
      'Budget': project.budget ? `$${project.budget.toLocaleString()}` : 'N/A',
  'Start Date': formatDate(project.startDate),
  'End Date': formatDate(project.endDate),
      'Progress %': `${(project.progress * 100).toFixed(1)}%`,
      'Team Size': teamSize,
      'Total Weekly Hours': totalHours,
      'Jira Project': project.jiraProjectKey || 'Not Linked'
    }
  })
  
  const exportData: ExportData[] = [
    {
      sheetName: 'Resource Allocations',
      data: allocationData
    },
    {
      sheetName: 'Consultant Summary',
      data: consultantSummary
    },
    {
      sheetName: 'Project Summary',
      data: projectSummary
    }
  ]
  
  generateXLSXReport(exportData, 'resource_allocation_matrix')
}